version: '3'

services:
  db:
    image: mysql:8.0
    container_name: ec-cube_db
    environment:
      MYSQL_DATABASE: eccube_db
      MYSQL_USER: testuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    volumes:
      - mysql-data:/var/lib/mysql
      - ./dockerbuild/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - 3307:3306

  app:
    build:
      context: ./
      dockerfile: ./dockerbuild/Dockerfile
    container_name: ec-cube
    volumes:
      - ./:/var/www/html/:cached
    ports:
      - 8080:80
      - 4430:443
    stdin_open: true
    tty: true
    depends_on:
      - db
    links:
      - db

volumes:
  mysql-data:
    driver: local